import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import AboutUs from '../components/about-us'
import Client from '../components/client'
import Contact from '../components/contact'
import Footer from '../components/footer'
import Gallery from '../components/gallery'
import Header from '../components/header'
import Info from '../components/info'
import Service from '../components/service'
import Slider from '../components/slider'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Mai Organizasyon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="hero_area">
        <div className="hero_bg_box">
          <img src="images/hero-bg.jpg" />
        </div>
        <Header />
        <Slider />
      </div>

      <AboutUs />
      <Service />
      <Gallery />
      <Contact />
      <Client />
      <Info />
      <Footer />
    </>
  )
}

export default Home
